Update php.yml

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -35,30 +35,13 @@ jobs:
           -e 's/;extension=sodium/extension=sodium/'
           -e 's/;extension=zip/extension=zip/'
           -e "s|curl\.cainfo.*|curl.cainfo=\"$REPO_ROOT/cacert.pem\"|"
-          -e "s|openssl\.cafile.*|openssl.cafile=\"$REPO_ROOT/server/apache/bin/curl-ca-bundle.crt\"|"
+          -e "s|openssl\.cafile.*|openssl.cafile=\"$REPO_ROOT\"/server/apache/bin/curl-ca-bundle.crt|"
           -e '$a\\max_input_vars=5000'
           -e '$a\\memory_limit_256M'
           -e '$a\\post_max_size=50M'
           -e '$a\\upload_max_filesize=50M'
           -e '$a\\extension=phar.so'
           server/php/php.ini
-
-      # - name: Set up php.ini
-      #   run: >
-      #     REPO_ROOT="`pwd`"
-      #     sed -i
-      #     -e 's/;extension=gd/extension=gd/'
-      #     -e 's/;extension=intl/extension=intl/'
-      #     -e 's/;extension=sodium/extension=sodium/'
-      #     -e 's/;extension=zip/extension=zip/'
-      #     -e "s|curl\.cainfo.*|curl.cainfo=\"$REPO_ROOT/cacert.pem\"|"
-      #     -e "s|openssl\.cafile.*|openssl.cafile=\"$REPO_ROOT\"/server/apache/bin/curl-ca-bundle.crt|"
-      #     -e '$a\\max_input_vars=5000'
-      #     -e '$a\\memory_limit_256M'
-      #     -e '$a\\post_max_size=50M'
-      #     -e '$a\\upload_max_filesize=50M'
-      #     -e '$a\\extension=phar.so'
-      #     server/php/php.ini
 
       # - name: Install composer
       #   run: |
@@ -84,6 +67,11 @@ jobs:
           export PHPRC=`realpath server/php/php.ini`
           cd server/moodle
           php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+          # Verify that the file was downloaded
+            if [ ! -f "composer-setup.php" ]; then
+              echo "Error: composer-setup.php file not found!"
+              exit 1
+            fi
           php composer-setup.php
           php -r "unlink('composer-setup.php');"
           sudo mv composer.phar /usr/local/bin/composer
